export const CropPlanKeysToNames = {
  originalEstimate: ['Original Plan', 'Total Acres'],
  originalEstimatePerAcre: ['Original Plan', 'Per Acre'],
  currentEstimate: ['Current Plan', 'Total Acres'],
  currentEstimatePerAcre: ['Current Plan', 'Per Acre'],
  totalCost: ['Projected Cost', 'Total Acres'],
  totalCostPerAcre: ['Projected Cost', 'Per Acre'],
  committedCost: ['Committed Cost', 'Total Acres'],
  committedCostPerAcre: ['Committed Cost', 'Per Acre'],
  actualCost: ['Actual Cost', 'Total Acres'],
  actualCostPerAcre: ['Actual Cost', 'Per Acre'],
  wipBalance: ['WIP Balance'],
  wipInput: ['WIP Input'],
  costsToComplete: ['Costs to Complete', 'Total Acres'],
  costsToCompletePerAcre: ['Costs to Complete', 'Per Acre'],
  overUnder: ['Over/Under'],
  projCostComplete: ['Proj. Cost Complete'],
  projectedEstimate: ['Projected Plan'],
}
