export const CropPlanKeysToNames = {
  originalEstimate: ['Original Plan', 'Total Acres'],
  originalEstimatePerAcre: ['Original Plan', 'Per Acre'],
  currentEstimate: ['Current Plan', 'Total Acres'],
  currentEstimatePerAcre: ['Current Plan', 'Per Acre'],
  totalCost: ['Projected Cost'],
  committedCost: ['Committed Cost'],
  actualCost: ['Actual Cost'],
  wipBalance: ['WIP Balance'],
  wipInput: ['WIP Input'],
  costsToComplete: ['Costs to Complete'],
  overUnder: ['Over/Under'],
  projCostComplete: ['Proj. Cost Complete'],
  projectedEstimate: ['Projected Plan'],
}
